language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - printf "\n" | pecl install imagick
  - composer install --no-interaction
  - cp config.dist.ini config.ini
  - php generate-key.php

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: 9917e59b0a22571bbc2a15b06bf0d21fbffc49e418fdebcb689745d91bdb2e4c
